### ISSUE TITLE
Non-Software idea to make mod better

### ISSUE THREAD

**Issue by TheGarretThief** [AndrisBorbas/FactorioMiningAndCraftingSpeed#1]
Maybe you should make your mod more realistic and less cheater? Not you think? 
In programming, I'm a complete zero, but I was able to correct the coefficients using the poke method)
I think something like this would make Your mod more usable in simple Factorio gaming)
[epic_mining_and_crafting_speed_research_7.0.0.zip](https://github.com/AndrisBorbas/FactorioMiningAndCraftingSpeed/files/5147057/epic_mining_and_crafting_speed_research_7.0.0.zip)

**Comment by AndrisBorbas** [comment]
That was a bit rough, but anyway, the thing that fooled me is that now the modifier is additive not just overwrites the last one in the chain. I'll admit mine is a bit fast, but your modification is too slow for my taste. I'll try adding an option menu to have the ability to adjust it.
